Draft: Velp scroll areas
TIM-JYU/TIM pull request #3086
Opened 2022-06-29 09:52 UTC by saviit

Minor visual overhaul and fixes to Velp menu and annotations. Resolves and mitigates issues #2647 and #3080 especially for smaller screens and display resolutions (or scaling factors > 1.0).

Changes:
- make most container elements in Velp menu scrollable in order to conserve screen space
- change/modify selection elements to more space-efficient types (eg. radio buttons -> dropdown menu)
- reposition elements into a more space-efficient flow

2022-06-29 09:55 UTC, saviit commented
Itse velp testit menevät läpi (kuvat on päivitetty jo). Usercontact-testin kuvat jostain syystä eivät asetu (vaikka näihin ei ole tämän haaran osalta koskettu).

2022-06-29 11:19 UTC, dezhidki requested changes
Sain toistettua epäonnistuneen usercontact-testin, laitoin siitä huomion muiden sekaan.

2022-06-29 11:19 UTC, dezhidki commented on timApp/static/stylesheets/velpSelection.scss
> +    }
Tämä nyt vaikuttaa kaikkin `form-group`eihin, joita on käytössä TIMissa kaikkialla (koska se on Bootstrapin yleinenluokka). `stylesheets`-kansion alla olevat tyylit ovat globaalit, eli niissä kannattaa laittaa aina melko tarkat tyylimääritteet mahdollisten "vuotojen" estämiseksi. 

Käytännössä tämä aiheuttaa esimerkiksi sen, että `usercontact`-testi epäonnistuu rikkinäiseen kuvaan: lataamalla [automaattitestien kuvat](https://github.com/TIM-JYU/TIM/suites/7140446452/artifacts/283855475) ja vertaamalla se [odotettuun kuvaan](https://github.com/TIM-JYU/TIM/blob/master/timApp/tests/browser/expected_screenshots/usercontact/add_new_unverified.png) niin huomaa eroja välistyksessä (katso esim. marginaali tekstikentän ja alertin välillä).

Epäonnistuneet testit taitavat johtua siitä, että automaattitestit ajetaan selaimessa, jonka resoluutio on 600x800, eli tämä mediavalitsin astuu voimaan juuri CI-testeissä. 
Ehdotan korjaamaan SCSSää, jotta tämä `.form-group`-muutos pätee vain velppeihin (ehkä jotenkin tarkempi valitsin).

2022-06-29 12:26 UTC, saviit commented on timApp/static/scripts/tim/velp/annotation.component.scss
> +  /* background: transparent;*/
Joo, tämä oli unohtunut poistaa tuolta, poistettu nyt.

2022-06-29 12:27 UTC, saviit commented on timApp/static/stylesheets/velpSelection.scss
> +    //width: 18em;
Poistettu.

2022-06-29 12:27 UTC, saviit commented on timApp/static/stylesheets/velpSelection.scss
> +    //border-bottom: 1px solid gainsboro;
Poistettu.

2022-06-29 12:28 UTC, saviit commented on timApp/static/stylesheets/velpSelection.scss
> +    }
Joo, tämäpä oli livahtanut ohi, korjattu nyt.

2022-06-29 12:59 UTC, dezhidki commented
En ole 100% varma, menikö nyt koko velppivalikko liian kapeaksi kaikkien siirtojen jälkeen. Ainakin itselläni Chromella:

![image](https://user-images.githubusercontent.com/5202606/176436851-76426dd9-eb49-4bc5-933f-da74720f1e8e.png)

tuossa tulee aika herkästi skrollailua. Mietin, pitäisiko kasvattaa minikorkeutta (tai suoraan `height`-attribuuttia, jolloin resizella sen voi laittaa pienemmäksi), niin tulee koko alue käyttöön.

Ideaalisesti tämän tabin asettelu pitäisi ehkä muuttaa flexboxiksi tai CSS grid:ksi, jolloin voi tarkasti säätää, miten koko dialogin korkeus jaetaan eri "osien" kesken. Mutta ei tarvi nyt tähän PRään kokonaan asettelua muuttaa; ehkä siinä vaiheessa, kun muutetaan tämä dialogi Angular-dialogiksi.

2022-06-29 13:05 UTC, dezhidki commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Joo, ja ainakin mielestäni olisi järkevämpi, että tämä "uusi velppi" olisi kiinni velppidialogissa eikä siis tuossa "Available velps" kohdassa. Nyt taitaa käydä niin, että jos "Available velps" on irrotettu ja painaa "Create new velp", se avaa uuden velppidialogin irrotettuun osaan missä se sattuukin olemaan. 

Sitten lisätilaa saa hyvin ottamalla Available velps omaksi alidialogiksi ja pitämällä luomiseen liittyvät osat päädialogissa:

![image](https://user-images.githubusercontent.com/5202606/176443203-b0e56879-d487-44f2-8d70-0cbff36fc773.png)

esim tämä nyt veisi max 450px korkeutta, ja luomisdialogi näkyy ihan hyvin ilman tarvetta laajentaa Available velps -alidialogia.

2022-06-29 13:09 UTC, dezhidki commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Pitänee varmaan odottaa, että Vesakin ehtii tuota katsomaan ja antaa mielipiteensä. Ainakin itse mietin, että tuolla sen saisi melko kompaktiksi ilman sitä, että velppien luomisdialogia tarvitsisi skrollata missään vaiheessa.

2022-06-29 13:10 UTC, saviit commented
Joo, Vesan palautteen perusteella olen tuossa yrittänyt mahduttaa tuota edes jollain järkevällä tavalla pienemmille näytöille. Ongelmiahan tässä nykyisessä layoutissa tulee väkisinkin, etenkin jos syystä tai toisesta käytetään skaalausta: 

![1280x800px ,125% skaalaus](https://user-images.githubusercontent.com/46485327/176443765-48079c47-9bff-414a-8bd2-8e6697abb112.PNG)

Esimerkkikuvassa siis 1280x800 resoluutio ja varmuuden vuoksi vielä 125 % skaalausta päälle. Tämä on oikeastaan se taso, mistä lähdin liikkeelle, kun aikaisemmat yritykset eivät tuottaneet haluttua tulosta.

2022-06-29 13:19 UTC, dezhidki commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Kokeilin vielä 800px korkeudella + 130% zoom ennen kuin ehdin laittaa minun devtools-kokeilut kiinni:

![image](https://user-images.githubusercontent.com/5202606/176445470-c8e97a7c-b14e-4707-b721-70bc315dc475.png)

Ja jos pitää kaikki yhdessä:

![image](https://user-images.githubusercontent.com/5202606/176445779-e5f40ccb-93ff-4a1f-9889-f9bf8f6765c6.png)

Ja vielä ennen kuin suljin kokeilut: siirsin siis selaimen devtoolsilla `<velp-window>`in `velpArea`aan:

![image](https://user-images.githubusercontent.com/5202606/176446074-af744396-9ed2-4143-8a89-da43b0791665.png)

2022-06-29 13:22 UTC, saviit commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Joo, tuohan näyttää fiksulta, minäpäs jatkan huomenna tuon pohjalta vielä.

2022-06-30 09:17 UTC, saviit commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Tämä nyt tehty ja kokeiltavissa myös timdevsissa. Nopealla testailulla editoitavan velpin editointi-ikkunan siirtäminen tim-draggablen ulkopuolelle ei ehkä ole yhtään näin helppo. Vaatinee joko DOMin käpisteltyä käsin tai velp-window-templaten uudelleenkirjoittamisen?

2022-06-30 09:29 UTC, saviit commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Niin tai tässä siirrettiin uuden velpin luomis/editointi-ikkunan tuonne `tim-draggable-fixed`:in ulkopuolelle. Tämä vaikuttaa ainoastaan uusiin velppeihin. Jos halutaan editoida aiemmin luotua velppiä, niin se tapahtuu edelleen tuon `tim-draggable-fixed`:in sisällä, koska `velpWindow`-tamplate on rakennettu niin.

Tämä ei ehkä ole hirveän paha, koska tosiaan tuon ikkunan voi irrottaa omakseen ja isontaa. Mutta toisaalta olisi kiva, jos tuo editointi-ikkuna tulisi aina samaan paikkaan tuonne `velpArea`:n sisään.

2022-06-30 09:47 UTC, dezhidki commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Ahaa, okei.

So on toki vähän ikävä, että editointinäkymä ei tule täysin esille siinä. Mutta tuon saa ehkä CSSllä vielä kikkailtua. Esim. jos laittaa `velp-window`:lle devtoolsilla

```
z-index: 10;
position: fixed;
```

niin tulee oikeansuuntaista tavaraa

![image](https://user-images.githubusercontent.com/5202606/176645233-55ded9e4-3958-4aec-999e-1cf81ebc0c09.png)

Siinä toki sitten ei saa käyttää `top`ia, muuten editointinäkymä lukittuu selaimen ylälaitaan. Olisiko joka tapauksessa toimivan näköinen?

Eli voisi kokeilla ehkä siten, että `VelpWindowController`:ssa asettaa editointitilassa jonkun luokan päälle (esim. `this.element.addClass("edit-mode")` funktioon `VelpWindowController.toggleVelpToEdit`), jolla voi sitten tyylittää editointitilassa olevaa `velp-window`ia.

2022-06-30 11:57 UTC, saviit commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Kylläpä tämä itse asiassa saattaa onnistua samalla tempulla kuin uuden velpin luominen; yritin aikaisemmin väärän muuttujan kautta saada kiinni velpiä/sen kontrollia, mutta vähän kaivelemalla löytyi oikea.

![edit-velp](https://user-images.githubusercontent.com/46485327/176669984-394b1191-aeed-44e2-8334-a77ecd41e533.png)

Haasteena nyt on löytää tapaa, jolla tuo editointi-ikkuna ei aukea tuonne `tim-draggable-fixed`:in sisään ollenkaan, vaan ainoastaan tuonne `velpArea`:n jälkeen. `z-index`stä ei tähän ollut apuja, koska se asettuu molemmille samaksi:

![edit-velp-samassa](https://user-images.githubusercontent.com/46485327/176671497-a99e6a43-e953-436d-9104-023c9c9ff383.png)

2022-06-30 12:08 UTC, dezhidki commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Tarkennuksena: mielestäni siis olemassa olevan velpin editointi ei kannata ehkä liittää itse "Velp menu"-ikkunaan vaan "Available velps"-ikkunaan, koska velppi on jo olemassa siinä. Muuten tulisi liikaa hyppyjä, jos olemassa olevan velpin muokkaus tapahtuu eri ikkunassa kuin missä se on määritelty. Sen sijaan uuden velpin luonnissa se editointivelppi voi olla "Velp menu"-ikkunassa, koska "Create velp"-painike on siellä.

Eli siis lopputulos olisi jotenkin seuraava:

[esimerkki.webm](https://user-images.githubusercontent.com/5202606/176673327-b3e36971-887c-4e93-b391-dd6f6820f560.webm)

Tai ajattelitko siis, että tuo editointivelppi tulee aina siihen "Velp menu"-ikkunaan?

Tuliko siis jotain ongelmia vastaan sen kanssa, että yrittää antaa "Available velps"-ikkunassa oleville velpeille tuo `position: fixed`, kun siitä avataan editointitila? Siinä toki joutuu erottelemaan, onko `velp-window` Available velps-ikkunassa tai onko se tuo `velpArea`:n sisällä oleva velppi, että se `position: fixed` + `z-index: 10` (tai voi laittaa korkeampi, jotta se on varmasti päällimmäisenä). Tämän voisi ehkä tehdä laittamalla `velp-window`:lle joku attribuutti (esim. `fixPositionOnEdit`). Voit katsoa `velpWindow.ts`:stä mallia esim. [miten AngularJS-komponenteille annetaan uusia attribuutteja](timApp/static/scripts/tim/velp/velpWindow.ts#L586).

2022-06-30 12:41 UTC, dezhidki commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Joo, kyllä se vähän joutuu skrollailemaan. Mutta sinänsä en näe tuota ihan mahdottoman pahana ongelmana, koska käyttäjän pitää muutenkin skrollata se velppi näkyviin, jotta hän voi paintaa tuota editointipainiketta. Tuolla ainakin saa edes jotenkin varmistettua, että editointimenu ei ole ihan piilossa.

Toisaalta nyt kun muistelen, niin tuo pinomaisuus tulee siitä, että `velp-window > .velp`-elementille asetetaan `top`-tyyliattribuutiksi `1+index*2`em. Eli onnistuisiko niin, että samalla kuin tekee luokan, joka asettaa tuon `position: fixed`, niin samalla tuolla luokalla resetoidaan top-attribuutti. Toimisikohan joku tällainen

```scss
velp-window.velp-edit-available {
  z-index: 10;
  position: fixed;

  & > .velp {
    top: 1em; // Ei oteta 0ksi, jotta se ei mene raahauspalkin päälle
  }
}
```

ja sitten kun painetaan kynästä, niin komponentille kytketään tuo `.velp-edit-available`.
Voidaan vaikka testata yhdessä minun Zoomissa, jos haluat.

2022-06-30 13:10 UTC, saviit commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Unohdin tosin tarkistaa ensin, mistä containerista editoitava velppi löytyy niin nyt uuden velpin editointi-ikkuna nousee turhan ylös. Sen korjaaminen jääköön huomiselle. :)

2022-06-30 13:14 UTC, dezhidki commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Joo, ja nyt taitaa myös käydä niin, että `top: 1em` jää elementtiin asetettavaan `top`:n varjoon johtuen CSS:n logiikasta (suoraan elementtiin tulevat tyylit menevät aina luokkien kautta tulevien tyylien edelle). Eli samalla pitäisi varmaan laittaa `top: 1em !important`. 

Ja en siis tiedä, onko 1em liikaa :)

2022-06-30 13:15 UTC, saviit commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
> Sen korjaaminen jääköön huomiselle. :)

En malttanut odottaa, tämä korjattu myös.

2022-06-30 13:18 UTC, dezhidki commented on timApp/static/stylesheets/velpSelection.scss
> +    top: 1em; // Ei oteta 0ksi, jotta se ei mene raahauspalkin päälle
Tähän tosiaankin varmaan vielä `top: 1em !important;`, koska nyt koodissa `top` asetetaan suoraan elementille, joten sen varo ylikirjoittaa CSS:n arvon. `!important`-määreellä saa pakotettua tämän arvon aina käyttöön. 

Sitten varmaan tuo suomenkielinen kommentti ottaa pois tai kääntää. Laitoin sen kommentteissa vain selitykseksi.

2022-06-30 13:20 UTC, dezhidki commented on timApp/static/templates/velpSelection.html
> +                                     advanced-on="$ctrl.advancedOn"></velp-window>
Joo, mielestäni näyttää nyt aika hyvältä. Laitoin tuon `top: 1em` kommentin omaksi ketjuksi. Laitan tämän resolvetuksi puolestani.

2022-06-30 13:33 UTC, saviit commented on timApp/static/stylesheets/velpSelection.scss
> +    top: 1em; // Ei oteta 0ksi, jotta se ei mene raahauspalkin päälle
Joo, huomasin tuon kommentin vähän myöhässä. Korjattu nyt.

2022-07-01 05:34 UTC, dezhidki approved these changes
Minun puolestani näyttää koodin kannalta hyvältä.

Tässä haarassa on nyt aika monta merge-committia masterista. Se hankaloittaa jonkin verran commit-historian lukemista (etenkin kun tämä mergetään masteriin, jolloin nämä master -> haara commitit olisivat aika turhat). Näin isoissa PRssä masterin mergen sijaan on parempi tehdä rebase, jolloin näitä mergecommitteja ei tule ja historia pysyy puhtaana.

Jälkikäteen voi myös aina hieman puhdistaa historiaa jonkin verran litistämällä yhteen kuuluvat commitit yhteen (gitissa käytetään käsitettä "squash").
PyCharmin omassa Git UIssa on olemassa esimerkiksi "Pull into 'haara' Using Rebase", jolla koodin pullaus masterista voi tehdä rebasella. Vastaavasti PyCharmissa voi tehdä litistämisen ja yksittäisten committien tekstien päivittämisen. Git-komennolle löytyy myös jonkun verran ohjeita, tässä mielestäni ihan hyviä:

* [`git pull --rebase` ja `git pull --merge`](https://sdqweb.ipd.kit.edu/wiki/Git_pull_--rebase_vs._--merge)
* [Write Better Commits, Build Better Projects](https://github.blog/2022-06-30-write-better-commits-build-better-projects) - Siinä on aika paljon aiheen vierestä, mutta itse mielenkiinnon kohde on "How do I do it?"-laatikot. Siinä annetaan esimerkkejä tavoista käyttää `git rebase -i`ta commit-historian siivoamiseksi

En nyt usko, että se nyt tähän ole tarvetta tehdä (ellei halua sitten lokaalisti leikkiä ja kokeilla). Teen nyt niin, että mergeän tämän squash:lla, jolloin GitHub automaattisesti yhdistää ja ottaa pois nämä mergecommitit. Siinä on toki se haitta, että alkuperäinen historia katoaa, mikä voi vaikeuttaa jatkossa debuggausta. Tässä tapauksessa se ei ole kuitenkaan kriittistä.

2022-07-01 05:36 UTC, merged

2022-07-01 05:40 UTC, dezhidki commented
En huomannut muuten, että tuossa olikin "Draft:"-teksti otsikossa. GitHubissa PR pitää merkitä Draft-tilaan erikseen (eli ei riittä vain otsikon vaihdos, vaan [pitää PR:n luomisvaiheessa valita Draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/). No tämä nyt meni masteriin, mielestäni oli joka tapauksessa ihan valmis.